experiment:
  seed: 28
  num_epochs: 120
  batch_size: 64

modalities:
  inertial:
    model:
      imuformer:
        class_name: IMUFormer
        from_module: IMUFormer
        encoder_class_name: IMUFormer
        encoder_name: imuformer
        args: []
        kwargs:
          d_model: 256
          num_layers: 3
          heads: 4
          _heads: 6
          sample_length: 60
          in_channels: 12
          dropout: 0.1
          pe_k: 40
          cnn_units: 6
          cnn_kernel_sizes: [[1,1], [7,7], [9,9]]
          batch_size: 32
          lr: 0.001
          optimizer_name: "adam"
          metric_name: "accuracy"
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 60
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        from_module: general_transforms
        transform_name: to_float
        in_test: true

  skeleton:
    model:
      poseformer:
        class_name: PoseFormer
        from_module: PoseFormerV4
        encoder_class_name: PoseFormer
        encoder_name: poseformer
        args: []
        kwargs:
          sample_length: 60
          n_joints: 17
          input_channels: 2
          opt:
            layers: 6
            number_of_kept_frames: 60
            number_of_kept_coeffs: 60
            naive: false
          embed_dim_ratio: 64
          num_heads: 8
          mlp_ratio: 4
          qkv_bias: true
          drop_rate: 0.2
          attn_drop_rate: 0.02
          drop_path_rate: 0.02
          batch_size: 32
          lr: 0.001
          optimizer_name: "adam"
          metric_name: "accuracy"
    transforms:
      - class_name: VariableLengthRandomCrop
        from_module: skeleton_transforms
        in_test: false
        kwargs:
          crop_p: 0.7
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 60
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Jittering
        from_module: inertial_augmentations
        in_test: false
        kwargs:
          sigma: 0.01
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true 