experiment:
  seed: 28
  num_epochs_ssl: 100
  num_epochs_fine_tuning: 100
  batch_size_fine_tuning: 64

ssl:
  args: []
  kwargs:
    temperature: 0.2
    sample_length: 50
    batch_size: 64
    hidden: [256, 128]
    lr: 0.0007814
    optimizer_name_ssl: "adam"

modalities:
  inertial:
    model:
      transformer:
        class_name: SupervisedTransformer
        from_module: inertial
        encoder_class_name: CNNTransformer
        encoder_name: cnn_transformer
        args: []
        kwargs:
          sample_length: 50
          kernel_size: 5
          out_channels: [32, 64, 128]
          num_head: 2
          num_attn_layers: 2
          lr: 0.001
          optimizer_name: "adam"
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        from_module: general_transforms
        transform_name: to_float
        in_test: true

  skeleton:
    model:
      poseformerv4:
        class_name: PoseFormer
        from_module: PoseFormerV4
        encoder_class_name: PoseFormer
        encoder_name: poseformerv4
        args: []
        kwargs:
          sample_length: 50
          opt:
            layers: 12
            number_of_kept_frames: 50
            number_of_kept_coeffs: 20
            naive: true
          embed_dim_ratio: 16
          num_heads: 8
          mlp_ratio: 2.
          qkv_bias: true
          drop_rate: 0.09
          attn_drop_rate: 0.0263
          drop_path_rate: 0.000685
    transforms:
      - class_name: RecenterJoints
        from_module: skeleton_transforms
        in_test: true
        kwargs:
          anchor_joint_index: 2
      - class_name: NormalizeDistances
        from_module: skeleton_transforms
        in_test: true
        kwargs:
          anchor_joint_1_index: 1
          anchor_joint_2_index: 2
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true 