experiment:
  seed: 28
  num_epochs_ssl: 160
  num_epochs_fine_tuning: 60
  batch_size_fine_tuning: 64

ssl:
  args: []
  kwargs:
    temperature: 0.05374956711612659
    sample_length: 60
    batch_size: 16
    hidden: [256, 128]
    lr: 0.00016032389898943056
    optimizer_name_ssl: "adam"

modalities:
  inertial:
    model:
      imuformer:
        class_name: IMUFormer
        from_module: IMUFormer
        encoder_class_name: IMUFormer
        encoder_name: imuformer
        args: []
        kwargs:
          d_model: 256
          num_layers: 10
          heads: 8
          _heads: 1
          sample_length: 60
          in_channels: 12
          dropout: 0.16289112755251017
          pe_k: 30
          cnn_units: 6
          cnn_kernel_sizes: [[1,1], [3,3], [5,5]]
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 60
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        from_module: general_transforms
        transform_name: to_float
        in_test: true

  skeleton:
    model:
      poseformerv4:
        class_name: PoseFormer
        from_module: PoseFormerV4
        encoder_class_name: PoseFormer
        encoder_name: poseformerv4
        args: []
        kwargs:
          sample_length: 60
          n_joints: 17
          input_channels: 2
          opt:
            layers: 10
            number_of_kept_frames: 60
            number_of_kept_coeffs: 60
            naive: true
          embed_dim_ratio: 16
          num_heads: 16
          mlp_ratio: 6.0
          qkv_bias: true
          drop_rate: 0.015090783019285714
          attn_drop_rate: 0.02768223198850278
          drop_path_rate: 0.0346168739617063
    transforms:
      - class_name: VariableLengthRandomCrop
        from_module: skeleton_transforms
        in_test: false
        kwargs:
          crop_p: 0.7
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 60
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Jittering
        from_module: inertial_augmentations
        in_test: false
        kwargs:
          sigma: 0.01
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true 