experiment:
  seed: 28
  num_epochs_ssl: 150
  num_epochs_fine_tuning: 150
  batch_size_fine_tuning: 64

ssl:
  args: []
  kwargs:
    temperature: 0.2
    sample_length: 50
    batch_size: 64
    hidden: [256, 128]
    lr: 0.0001559439733088198
    optimizer_name_ssl: "adam"

modalities:
  inertial:
    model:
      imuformer:
        class_name: IMUFormer
        from_module: IMUFormer
        encoder_class_name: IMUFormer
        encoder_name: imuformer
        args: []
        kwargs:
          d_model: 32
          num_layers: 7
          heads: 16
          _heads: 2
          sample_length: 50
          dropout: 0.19943472457523329
          pe_k: 50
          cnn_units: 6
          cnn_kernel_sizes: [[1,1], [3,3], [5,5]]
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        from_module: general_transforms
        transform_name: to_float
        in_test: true

  skeleton:
    model:
      poseformerv4:
        class_name: PoseFormer
        from_module: PoseFormerV4
        encoder_class_name: PoseFormer
        encoder_name: poseformerv4
        args: []
        kwargs:
          sample_length: 50
          opt:
            layers: 8
            number_of_kept_frames: 50
            number_of_kept_coeffs: 50
            naive: false
          embed_dim_ratio: 64
          num_heads: 8
          mlp_ratio: 6.0
          qkv_bias: true
          drop_rate: 0.13486986785243843
          attn_drop_rate: 0.02629266491207646
          drop_path_rate: 0.020530600737858742
    transforms:
      - class_name: RecenterJoints
        from_module: skeleton_transforms
        in_test: true
        kwargs:
          anchor_joint_index: 2
      - class_name: NormalizeDistances
        from_module: skeleton_transforms
        in_test: true
        kwargs:
          anchor_joint_1_index: 1
          anchor_joint_2_index: 2
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true 