program: cmc_da_training.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  # SSL hyperparameters
  lr_cmc:
    distribution: log_uniform_values
    min: 1e-5 
    max: 1e-2
  lr_da:
    distribution: log_uniform_values
    min: 1e-5 
    max: 1e-2
  ssl_batch_size:
    values: [16, 32]
  ssl_temperature:
    distribution: uniform
    min: 0.05
    max: 0.2
  hidden_cmc:
    values:
      - [256, 128]
      - [512, 256]
      - [128, 64]
  hidden_da:
    values:
      - [256, 128]
      - [512, 256]
      - [128, 64]
  beta:
    distribution: uniform
    min: 0.1
    max: 1.0
  
  # Fine-tuning hyperparameters
  ft_kwargs.lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-2
  ft_kwargs.hidden:
    values:
      - [256, 128]
      - [512, 256]
      - [128, 64]
  ft_kwargs.batch_size:
    values: [16, 32]

  # Number of epochs
  num_epochs_ssl:
    value: 2
  num_epochs_fine_tuning:
    value: 2

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --experiment_config_path
  - configs/cmc_da/cmc_da_utd.yaml
  - --dataset
  - utd_mhad
  - --data_path
  - processed_data/utd_mhad/multimodal_har_datasets/utd_mhad
  - --protocol
  - cross_subject
  - --framework
  - cmc_da
  - --modalities
  - inertial
  - skeleton
  - --models
  - transformer
  - transformer
  - --augmentations_path
  - configs/inertial_augmentations/augmentations_utd.yaml
  - configs/skeleton_augmentations/augmentations_utd.yaml
  - --gpus
  - 0
  - --sweep 