experiment:
  seed: 28
  num_epochs_ssl: 100             # pretraining epochs
  num_epochs_fine_tuning: 100     # fine tuning epochs
  batch_size_fine_tuning: 64

ssl:
  args: []
  kwargs:
    temperature: 0.2
#    sample_length: 50
    batch_size: 64
    hidden: [256, 128]
    lr: 0.0007814
    optimizer_name_ssl: "adam"
    lambda_da: 1.0
    da_kwargs:
      weight_spatial: 1.0
      weight_temporal: 1.0
      beta: 0.5
      iteration: 50
      common_dim: 512

modalities:
  inertial:
    model:
      imuformer:
        class_name: IMUFormer
        from_module: IMUFormer
        encoder_class_name: IMUFormer
        encoder_name: imuformer
        args: []
        kwargs:
          d_model: 128
          num_layers: 5
          heads: 4
          _heads: 2
          sample_length: 50
          dropout: 0.0353
          pe_k: 20
          cnn_units: 1
          cnn_kernel_sizes: [[1,1], [3,3], [5,5]]
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        from_module: general_transforms
        transform_name: to_float
        in_test: true

  skeleton:
    model:
      poseformerv4:
        class_name: PoseFormer
        from_module: PoseFormerV4
        encoder_class_name: PoseFormer
        encoder_name: poseformerv4
        args: []
        kwargs:
          sample_length: 50
          opt:
            layers: 12
            number_of_kept_frames: 50
            number_of_kept_coeffs: 20
            naive: false
          embed_dim_ratio: 16
          num_heads: 8
          mlp_ratio: 2.
          qkv_bias: true
          drop_rate: 0.09
          attn_drop_rate: 0.0263
          drop_path_rate: 0.000685
    transforms:
      - class_name: RecenterJoints
        from_module: skeleton_transforms
        in_test: true
        kwargs:
          anchor_joint_index: 2
      - class_name: NormalizeDistances
        from_module: skeleton_transforms
        in_test: true
        kwargs:
          anchor_joint_1_index: 1
          anchor_joint_2_index: 2
      - class_name: SkeletonSampler
        from_module: skeleton_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 50
      - class_name: ToTensor
        from_module: general_transforms
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        in_test: true
        kwargs:
          shape: [1, 2, 0]
      - class_name: ToFloat
        from_module: general_transforms
        in_test: true