program: ssl_training_mm.py
name: cmc_da_sslparam_imupose_sweep_utd
command:
  - python
  - ssl_training_mm.py
  - --experiment_config_path
  - configs/cmc_da/cmc_da_imuformer_poseformer_utd.yaml
  - --dataset_config_path
  - configs/dataset_configs.yaml
  - --dataset
  - utd_mhad
  - --data_path
  - processed_data/utd_mhad/multimodal_har_datasets
  - --augmentations_path
  - configs/inertial_augmentations/augmentations_utd.yaml
  - configs/skeleton_augmentations/augmentations_utd.yaml
  - --modalities
  - inertial
  - skeleton
  - --models
  - imuformer
  - poseformerv4
  - --num-workers
  - 32
  - --framework
  - cmc-da
  - --sweep
method: bayes
metric:
  name: ssl_val_loss
  goal: minimize
parameters:
  ssl.temperature:
    distribution: uniform
    min: 0.05
    max: 0.5
  ssl.lr:
    distribution: uniform
    min: 0.00001
    max: 0.001
  ssl.batch_size:
    values: [16, 32, 64]
  ssl.da_kwargs.beta:
    distribution: uniform
    min: 0.1
    max: 0.7
  ssl.da_kwargs.iteration:
    distribution: int_uniform
    min: 10
    max: 100
  ssl.da_kwargs.weight_spatial:
    distribution: uniform
    min: 0.5
    max: 1.5
  ssl.da_kwargs.weight_temporal:
    distribution: uniform
    min: 0.5
    max: 1.5 