experiment:
  seed: 28
  num_epochs_ssl: 200
  num_epochs_fine_tuning: 120
  batch_size_fine_tuning: 64

modalities:
  inertial:
    model:
      imuformer:
        class_name: IMUFormer
        from_module: IMUFormer
        encoder_class_name: IMUFormer
        encoder_name: imuformer
        args: []
        kwargs:
          d_model: 256
          num_layers: 3
          heads: 4
          _heads: 6
          sample_length: 60
          dropout: 0.08553562864390574
          pe_k: 40
          cnn_units: 6
          cnn_kernel_sizes: [[1,1], [7,7], [9,9]]
          batch_size: 32
      ssl:
        class_name: SimCLRUnimodal
        from_module: simclr_um
        kwargs:
          hidden: [256, 128]
          batch_size: 32
          temperature: 0.1
          n_views: 2
          optimizer_name_ssl: lars
          lr: 0.00020786739595865915
    transforms:
      - class_name: InertialSampler
        from_module: inertial_transforms
        transform_name: sampling
        in_test: true
        kwargs:
          size: 60
      - class_name: ToTensor
        from_module: general_transforms
        transform_name: to_tensor
        in_test: true
      - class_name: Permute
        from_module: general_transforms
        transform_name: permutation
        in_test: true
        kwargs:
          shape: [1, 0]
      - class_name: ToFloat
        from_module: general_transforms
        transform_name: to_float
        in_test: true 